export const FETCH_PIZZA = 'FETCH_PIZZA'
export const FETCH_PIZZA_SUCCESS = 'FETCH_PIZZA_SUCCESS'
export const FETCH_PIZZA_ERROR = 'FETCH_PIZZA_ERROR'

export const FETCH_TOPPING = 'FETCH_TOPPING'
export const FETCH_TOPPING_SUCCESS = 'FETCH_TOPPING_SUCCESS'
export const FETCH_TOPPING_ERROR = 'FETCH_TOPPING_ERROR'

export const CURRENT_PIZZA_CHANGE = 'CURRENT_PIZZA_CHANGE'
export const CURRENT_SIZE_CHANGE = 'CURRENT_SIZE_CHANGE'
export const CURRENT_TOPPINGS_CHANGE = 'CURRENT_TOPPINGS_CHANGE'

export const CART_ADD_CURRENT = 'CART_ADD_CURRENT'
